headers:
  rules:
    # This set of rules is related to caching
    - type: header
      header: Cache-Control
      errors:
        presence: true
        regex: !!js/regexp /max-age=\d+/
    - type: header
      header: Vary
      errors:
        presence: true
        regex: !!js/regexp /Accept-Encoding/
    - type: header
      header: Etag
      errors:
        presence: true
    - type: header
      header: Surrogate-Control
      errors:
        presence: true
        regex: !!js/regexp /public, ?max-age=\d+, ?stale-while-revalidate=\d+, ?stale-if-error=\d+/
    - type: header
      header: Surrogate-Key
      warnings:
        presence: true
        regex: !!js/regexp /./
    - type: header
      header: Set-Cookie
      errors:
        absence: true

    # These rules are related to compression
    - type: header
      header: Content-Encoding
      errors:
        presence: true
        regex: !!js/regexp /gzip/

seo:
  rules:
    # There should be exactly one title in head, and none in body
    - type: dom
      selector: head title
      contentAttr: body
      errors:
        presence: true
        count: 1
    - type: dom
      selector: body title
      contentAttr: body
      errors:
        count: 0

    # Should be exactly one h1
    - type: dom
      selector: body h1
      contentAttr: body
      errors:
        presence: true
        count: 1
      warnings:
        length_le: 66

    # Meta Description should be 160 chars or less, and be different from title
    - type: dom
      selector: meta[name=description]
      contentAttr: content
      errors:
        presence: true
        count: 1
        different_from:
          selector: head title
          contentAttr: body
      warnings:
        length_le: 160

    # Meta Lang Should Be Present
    - type: dom
      selector: html[lang]
      contentAttr: lang
      errors:
        presence: true
        length_le: 2

    # Meta Name=robots should not be there
    - type: dom
      selector: meta[name=robots]
      contentAttr: content
      errors:
        count: 0

    # Canonical should be presennt
    - type: dom
      selector: head link[rel=canonical]
      contentAttr: href
      errors:
        presence: true
        value: url

    # Every image should have an alt text
    - type: dom
      selector: img
      contentAttr: alt
      errors:
        presence_if_node_exists: true

    # Every iframe should have a src
    - type: dom
      selector: iframe
      contentAttr: src
      errors:
        presence_if_node_exists: true

    # Viewport should be present
    - type: dom
      selector: head meta[name=viewport]
      contentAttr: content
      errors:
        presence: true
        count: 1

    # URL should be https
    - type: url
      errors:
        regex: !!js/regexp /^https/

    # URL should not contain special characters and underscores
    # Alternatively, it should only contain lowercase letters, underscores and numbers
    - type: url
      errors:
        regex: !!js/regexp /^https?:\/\/[a-z0-9.\-_]+\/[a-z0-9\-\/]*$/

og:
  rules:
    - type: dom
      selector: meta[property=og\:type]
      contentAttr: content
      errors:
        presence: true
        count: 1
        length_le: 12
    - type: dom
      selector: meta[property=og\:title]
      contentAttr: content
      warnings:
        presence: true
        count: 1
        length_le: 66
    - type: dom
      selector: meta[property=og\:site_name]
      contentAttr: content
      warnings:
        presence: true
        count: 1
        length_le: 30

    # OG Image related
    - type: dom
      selector: meta[property=og\:image]
      contentAttr: content
      errors:
        presence: true
        count: 1
    - type: dom
      selector: meta[property=og\:image\:height]
      contentAttr: content
      warnings:
        presence: true
        count: 1
    - type: dom
      selector: meta[property=og\:image\:width]
      contentAttr: content
      warnings:
        presence: true
        count: 1

amp:
  ignored: true

structured:
  ignored: true
