headers:
  rules:
    # This set of rules is related to caching
    - type: header
      header: Cache-Control
      errors:
        presence: true
        regex: !!js/regexp /public, ?max-age=\d+/
    - type: header
      header: Vary
      errors:
        presence: true
        regex: !!js/regexp /Accept-Encoding/
    - type: header
      header: Surrogate-Control
      errors:
        presence: true
        regex: !!js/regexp /public, ?max-age=\d+, ?stale-while-revalidate=\d+, ?stale-if-error=\d+/
    - type: header
      header: Surrogate-Key
      warnings:
        presence: true
        regex: !!js/regexp /./
    - type: header
      header: Set-Cookie
      errors:
        absence: true

    # These rules are related to compression
    - type: header
      header: Content-Encoding
      errors:
        presence: true
        regex: !!js/regexp /gzip/
og:
  rules:
    - type: dom
      selector: meta[property=og\:type]
      contentAttr: content
      errors:
        presence: true
        count: 1
        length_le: 12
    - type: dom
      selector: meta[property=og\:title]
      contentAttr: content
      warnings:
        presence: true
        count: 1
        length_le: 66
    - type: dom
      selector: meta[property=og\:site_name]
      contentAttr: content
      warnings:
        presence: true
        count: 1
        length_le: 30

    # OG Image related
    - type: dom
      selector: meta[property=og\:image]
      contentAttr: content
      errors:
        presence: true
        count: 1
    - type: dom
      selector: meta[property=og\:image\:height]
      contentAttr: content
      warnings:
        presence: true
        count: 1
    - type: dom
      selector: meta[property=og\:image\:width]
      contentAttr: content
      warnings:
        presence: true
        count: 1

amp:
  ignored: true

structured:
  ignored: true
